### ISSUE TITLE
RuntimeError Could not locate a supported Microsoft Visual C++ installation

### ISSUE THREAD

**Issue by duping812** [sdbds/TRELLIS-for-windows#19]
After installation, the GUI can run in the web page. Upload a picture, click "Generate" button. The log shows sampling no prob, but stuck at rendering, error message as below:
```
.venv\lib\site-packages\nvdiffrast\torch\ops.py 
RuntimeError: Could not locate a supported Microsoft Visual C++ installation
```

After some research, I find the problem is VS build tools. The default setting did not install the required C++ tools. I have to modify the build tools installation and enable the Desktop development with C++ as below. 

After this mod, you will find the required tools installed at this location, which specified in find_cl_path() function of ops.py 
`C:\Program Files (x86)\Microsoft Visual Studio\*\*\VC\Tools\MSVC\*\bin\Hostx64\x64`

![desktop_development_with_cpp-2022](https://github.com/user-attachments/assets/43778594-eacf-45fa-9641-e1c74c03f435)

**Comment by sdbds** [comment]
Thank you for your reply! I will add it to the README.
