### ISSUE TITLE
Any way to get this to listen on lan ports? like --listen flag on other gradio webui.bat

### ISSUE THREAD

**Issue by bnelsey** [sdbds/TRELLIS-for-windows#4]
I'm trying to offload TRELLIS to a secondary pc since I can't really play games while it's doing its thing.
*This is also what I do with stable diffusion with the --listen flag in webui.bat

Since we use powershell to start this on windows I'm pretty much clueless where I'm supposed to put the --listen flag for gradio so I can use this over LAN

**Comment by sdbds** [comment]
Modify this line of code in the app.py file in your local directory:
`demo.launch()` to `demo.launch(share=True)`
https://github.com/sdbds/TRELLIS-for-windows/blob/c1c4d3f874948cf836d7a3957bab503f656a3031/app.py#L248
